FROM docker.io/library/debian:13-slim

ARG CHECK_TARGET=check-local

ENV DEBIAN_FRONTEND=noninteractive
# hadolint ignore=DL3008
RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        gcc libc-dev make clang-format clang-tidy; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*

WORKDIR /src
COPY src/ src/
COPY Makefile .
COPY .clang-format .
COPY .clang-tidy .

RUN make $CHECK_TARGET
